stages:
  - install
  - test
  - deploy_test
  - deploy_prod

.artifacts: &artifacts
  artifacts:
    paths:
      - .venv/

.image_test: &image_test
  image: paradoxxxzero/python-node-yarn-postgresql:latest

.retry: &retry
  retry: 1

install:
  stage: install
  <<: *image_test
  script:
    - make install
  <<: *artifacts

lint:
  stage: test
  <<: *image_test
  script: make lint
  <<: *retry
  dependencies:
    - install

test:
 stage: test
 <<: *image_test
 script:
   - make check
 <<: *retry
 dependencies:
   - install


.image: &image_deploy_jobs
  image: grewn0uille/deploy-tools:latest

deploy_test:
  <<: *image_deploy_jobs
  stage: deploy_test
  script:
    - make deploy-test
  dependencies: []

deploy_prod:
  <<: *image_deploy_jobs
  stage: deploy_prod
  script:
    - make deploy-prod
  dependencies: []
  only:
    - master
